server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Gzip compression settings
    gzip on;
    gzip_types 
        text/plain 
        text/css 
        application/json 
        application/javascript 
        application/xml 
        text/xml 
        application/xhtml+xml 
        application/rss+xml 
        image/svg+xml;
    gzip_proxied any;
    gzip_min_length 1000;
}
